import {
  IconActivity,
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowRight,
  IconArrowUpRight,
  IconBell,
  IconBold,
  IconBox,
  IconBrandGithub,
  IconBrandTwitter,
  IconBrightness,
  IconBuildingStore,
  IconCalendar,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircle,
  IconCircleCheck,
  IconCirclePlus,
  IconCircleX,
  IconClipboardText,
  IconClock,
  IconCode,
  IconChartBar,
  IconChartPie,
  IconCommand,
  IconCreditCard,
  IconDeviceLaptop,
  IconDots,
  IconDotsVertical,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileText,
  IconFileTypePdf,
  IconFileTypeDoc,
  IconFileTypeXls,
  IconFileZip,
  IconFolder,
  IconGripVertical,
  IconHelpCircle,
  IconInfoCircle,
  IconItalic,
  IconHeart,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLayoutSidebar,
  IconLoader2,
  IconLock,
  IconRefresh,
  IconLogin,
  IconLogout,
  IconLocation,
  IconListNumbers,
  IconMessage,
  IconMinus,
  IconMoon,
  IconMusic,
  IconPalette,
  IconPaperclip,
  IconPhone,
  IconPhoto,
  IconPizza,
  IconPlus,
  IconProps,
  IconReceipt,
  IconRosetteDiscountCheck,
  IconSearch,
  IconSelector,
  IconSend,
  IconSettings,
  IconShare,
  IconSlash,
  IconSparkles,
  IconStack2,
  IconStar,
  IconStethoscope,
  IconSun,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTypography,
  IconUnderline,
  IconUpload,
  IconUser,
  IconUserCheck,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconUsers,
  IconVideo,
  IconCrown,
  IconX,
  IconTruck,
  IconMapPin,
  IconFilter,
  IconPackageOff,
  IconArrowsSort,
  IconArrowsExchange,
  IconBike,
  IconBuildingWarehouse,
  IconCar,
  IconCurrentLocation,
  IconFlame,
  IconLayersSelected,
  IconMap,
  IconMapSearch,
  IconNavigation,
  IconRadar,
  IconRoad,
  IconRoute,
  IconTarget,
  IconWalk,
  IconWorld,
  IconPackage,
  IconDownload,
  IconCircleArrowUp,
  IconGift,
  IconFlask,
  IconPill,
  IconTicket,
  IconLayoutList,
  IconTable,
  IconInbox,
  IconCopy,
  IconMail,
  IconPlayerPause,
  IconPlayerPlay,
  IconQrcode,
  IconFileSpreadsheet,
  IconArrowsMaximize,
  IconArrowsMinimize
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  qrCode: IconQrcode,
  qrcode: IconQrcode,
  fileSpreadsheet: IconFileSpreadsheet,
  inbox: IconInbox,
  copy: IconCopy,
  mail: IconMail,
  pause: IconPlayerPause,
  play: IconPlayerPlay,
  maximize: IconArrowsMaximize,
  minimize: IconArrowsMinimize,
  image: IconPhoto,
  view: IconEye,
  horizontalSliders: IconAdjustmentsHorizontal,
  gift: IconGift,
  flask: IconFlask,
  pill: IconPill,
  ticket: IconTicket,
  layoutList: IconLayoutList,
  table: IconTable,
  alertCircle: IconAlertCircle,
  warning: IconAlertTriangle,
  arrowRight: IconArrowRight,
  check: IconCheck,
  checks: IconChecks,
  circleCheck: IconCircleCheck,
  close: IconX,
  clock: IconClock,
  code: IconCode,
  dots: IconDots,
  ellipsis: IconDotsVertical,
  externalLink: IconExternalLink,
  help: IconHelpCircle,
  info: IconInfoCircle,
  spinner: IconLoader2,
  search: IconSearch,
  settings: IconSettings,
  trash: IconTrash,
  download: IconDownload,
  status: IconCircleArrowUp,
  priority: IconArrowsSort,

  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronsDown: IconChevronsDown,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  chevronsUpDown: IconSelector,

  dashboard: IconLayoutDashboard,
  kanban: IconLayoutKanban,
  panelLeft: IconLayoutSidebar,

  user: IconUser,
  userCheck: IconUserCheck,
  user2: IconUserCircle,
  account: IconUserCircle,
  profile: IconUser,
  employee: IconUserX,
  userX: IconUserX,
  userPen: IconUserEdit,
  teams: IconUsers,

  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  logo: IconCommand,

  chat: IconMessage,
  notification: IconBell,
  phone: IconPhone,
  video: IconVideo,
  send: IconSend,
  paperclip: IconPaperclip,

  page: IconFile,
  post: IconFileText,
  fileTypePdf: IconFileTypePdf,
  fileTypeDoc: IconFileTypeDoc,
  fileTypeXls: IconFileTypeXls,
  fileZip: IconFileZip,
  media: IconPhoto,
  music: IconMusic,
  heart: IconHeart,

  add: IconPlus,
  edit: IconEdit,
  upload: IconUpload,
  arrowDown: IconDownload,
  refresh: IconRefresh,
  share: IconShare,
  login: IconLogin,
  logout: IconLogout,
  gripVertical: IconGripVertical,

  circle: IconCircle,
  circleX: IconCircleX,
  plusCircle: IconCirclePlus,
  xCircle: IconCircleX,
  minus: IconMinus,

  sun: IconSun,
  moon: IconMoon,
  brightness: IconBrightness,
  laptop: IconDeviceLaptop,
  palette: IconPalette,

  billing: IconCreditCard,
  creditCard: IconCreditCard,
  product: IconBox,
  catalog: IconBuildingStore,
  box: IconBox,
  pro: IconCrown,
  exclusive: IconStar,
  receipt: IconReceipt,
  sparkles: IconSparkles,
  badgeCheck: IconRosetteDiscountCheck,
  lock: IconLock,

  trendingDown: IconTrendingDown,
  trendingUp: IconTrendingUp,
  eye: IconEye,
  eyeOff: IconEyeOff,
  adjustments: IconAdjustmentsHorizontal,
  barChart: IconChartBar,
  pieChart: IconChartPie,

  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  text: IconTypography,

  toastSuccess: IconCircleCheck,
  toastInfo: IconInfoCircle,
  toastWarning: IconAlertTriangle,
  toastError: IconCircleX,
  toastLoading: IconLoader2,

  pizza: IconPizza,
  location: IconLocation,
  workspace: IconFolder,
  forms: IconClipboardText,
  slash: IconSlash,
  calendar: IconCalendar,
  galleryVerticalEnd: IconStack2,
  moreHorizontal: IconDots,

  truck: IconTruck,
  mapPin: IconMapPin,
  filter: IconFilter,
  packageX: IconPackageOff,
  arrowsSort: IconArrowsSort,
  arrowsExchange: IconArrowsExchange,
  bike: IconBike,
  warehouse: IconBuildingWarehouse,
  car: IconCar,
  currentLocation: IconCurrentLocation,
  flame: IconFlame,
  layers: IconLayersSelected,
  map: IconMap,
  mapSearch: IconMapSearch,
  navigation: IconNavigation,
  radar: IconRadar,
  road: IconRoad,
  route: IconRoute,
  target: IconTarget,
  walk: IconWalk,
  world: IconWorld,
  package: IconPackage,

  activity: IconActivity,
  listOrdered: IconListNumbers,
  stethoscope: IconStethoscope,
  arrowUpRight: IconArrowUpRight,
  star: IconStar
};
